from __future__ import annotations

RISK_HIGH_FEVER = "P0_RISK_HIGH_FEVER"
RISK_CHEST_PAIN = "P0_RISK_CHEST_PAIN"
RISK_DYSPNEA = "P0_RISK_DYSPNEA"
RISK_GI_BLEEDING = "P0_RISK_GI_BLEEDING"
RISK_CONSCIOUSNESS = "P0_RISK_CONSCIOUSNESS"
RISK_SEVERE_ABDOMINAL_PAIN = "P0_RISK_SEVERE_ABDOMINAL_PAIN"

ALL_RISK_RULE_IDS = [
    RISK_HIGH_FEVER,
    RISK_CHEST_PAIN,
    RISK_DYSPNEA,
    RISK_GI_BLEEDING,
    RISK_CONSCIOUSNESS,
    RISK_SEVERE_ABDOMINAL_PAIN,
]

__all__ = [
    "ALL_RISK_RULE_IDS",
    "RISK_CHEST_PAIN",
    "RISK_CONSCIOUSNESS",
    "RISK_DYSPNEA",
    "RISK_GI_BLEEDING",
    "RISK_HIGH_FEVER",
    "RISK_SEVERE_ABDOMINAL_PAIN",
]
